<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateCourseRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string|',
            'price' => 'required|integer|',
            'month_count' => 'required|integer|',
            'course_time' => 'required|integer|',
            'description' => 'required',
        ];
    }
    public function messages()
    {
        return [
            "name" => "コース名は必須です。",
            'price' => '価格は必須です。',
            'month_count' => 'コース回数は必須です。',
            'course_time' => 'コース時間は必須です。',
            'description' => 'コース説明は必須です。',
        ];
        // return parent::messages(); // TODO: Change the autogenerated stub
    }
}
